version: '3.7'

services:
  configserver:
    image: blessedsibanda/configserver:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
      - "8071:8071"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "configserver"

networks:
  backend:
    driver: bridge